"""SQLAlchemy ORM model for AI-generated and rule-based recommendations."""

from sqlalchemy import Float, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TimestampMixin, UUIDPrimaryKeyMixin


class Recommendation(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """A storage optimization recommendation generated by the rule engine or AI.

    Tracks the lifecycle of a recommendation from generation through
    acceptance/dismissal and eventual execution via the cleanup workflow.
    """

    __tablename__ = "recommendations"

    scan_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("scans.id", ondelete="SET NULL"), nullable=True
    )
    provider: Mapped[str] = mapped_column(String(20), nullable=False)
    model: Mapped[str | None] = mapped_column(String(50), nullable=True)
    category: Mapped[str] = mapped_column(String(30), nullable=False)
    priority: Mapped[str] = mapped_column(String(10), nullable=False)
    title: Mapped[str] = mapped_column(String, nullable=False)
    description: Mapped[str] = mapped_column(String, nullable=False)
    explanation: Mapped[str | None] = mapped_column(String, nullable=True)
    recoverable_bytes: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    confidence: Mapped[float] = mapped_column(Float, nullable=False, server_default="0.0")
    affected_paths: Mapped[str | None] = mapped_column(String, nullable=True)
    affected_count: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0"
    )
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, server_default="pending"
    )
    dismissed_reason: Mapped[str | None] = mapped_column(String, nullable=True)

    def __repr__(self) -> str:
        return (
            f"Recommendation(id={self.id!r}, title={self.title!r}, "
            f"priority={self.priority!r})"
        )
